export enum PageType {
  Home = 'Home',
  PLP = 'PLP',
  PDP = 'PDP',
  Search = 'Search',
  Cart = 'Cart',
  Checkout = 'Checkout',
  Blog = 'Blog',
  Account = 'Account',
  Category = 'Category',
  Promotions = 'Promotions',
}

export enum WidgetType {
  Banner = 'Banner',
  Carousel = 'Carousel',
  ProductGrid = 'ProductGrid',
  Footer = 'Footer',
  Navigation = 'Navigation',
  PromoCard = 'PromoCard',
  Reviews = 'Reviews',
  AddToCart = 'AddToCart',
  SearchBar = 'SearchBar',
  Filter = 'Filter',
  SocialLinks = 'SocialLinks',
  BlogPost = 'BlogPost',
}

export enum DataContractType {
  BannerContent = 'BannerContent',
  ProductGridContent = 'ProductGridContent',
  FooterContent = 'FooterContent',
  NavigationContent = 'NavigationContent',
  PromoCardContent = 'PromoCardContent',
  ReviewsContent = 'ReviewsContent',
  AddToCartContent = 'AddToCartContent',
  SearchBarContent = 'SearchBarContent',
  FilterContent = 'FilterContent',
  SocialLinksContent = 'SocialLinksContent',
  BlogPostContent = 'BlogPostContent',
}

export interface FragmentStyle {
  minHeight?: string;
  height?: string;
  maxHeight?: string;
  minWidth?: string;
  width?: string;
  maxWidth?: string;
  padding?: string;
  margin?: string;
  gap?: string;
  backgroundColor?: string;
  backgroundImage?: string;
  backgroundSize?: string;
  backgroundPosition?: string;
  border?: string;
  borderRadius?: string;
  boxShadow?: string;
  opacity?: string;
  display?: string;
  flexDirection?: string;
  flexWrap?: string;
  justifyContent?: string;
  alignItems?: string;
  gridTemplateColumns?: string;
  gridTemplateRows?: string;
  gridGap?: string;
  fontSize?: string;
  fontWeight?: string;
  color?: string;
  textAlign?: string;
  mobile?: Partial<FragmentStyle>;
  tablet?: Partial<FragmentStyle>;
  desktop?: Partial<FragmentStyle>;
}

export interface Fragment {
  id: string;
  name: string;
  pageType: PageType;
  style: FragmentStyle;
  allowedWidgets: WidgetType[];
  widget?: WidgetType;
  dataKey?: string;
  dataContractType?: DataContractType;
  order?: number;
  isUserDefined: boolean;
  tags?: string[];
  createdAt?: string;
  updatedAt?: string;
  children?: Fragment[];
}

const fragments: Fragment[] = [
  // Predefined Fragments for Home Page
  {
    id: 'home-header',
    name: 'Header',
    pageType: PageType.Home,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'hero-banner',
    name: 'Hero Banner',
    pageType: PageType.Home,
    style: {
      minHeight: '400px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundImage: 'url(/images/hero-bg.jpg)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      mobile: {
        minHeight: '300px',
        padding: '8px',
      },
       tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Banner, WidgetType.Carousel],
    dataKey: 'heroBannerContent',
    dataContractType: DataContractType.BannerContent,
    order: 1,
    isUserDefined: false,
    tags: ['hero', 'promo'],
  },
  {
    id: 'product-grid',
    name: 'Product Grid',
    pageType: PageType.Home,
    style: {
      minHeight: '300px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
      gap: '16px',
      mobile: {
        gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
        gap: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.ProductGrid],
    dataKey: 'productGridItems',
    dataContractType: DataContractType.ProductGridContent,
    order: 2,
    isUserDefined: false,
    tags: ['products'],
  },
  {
    id: 'cta-section',
    name: 'CTA Section',
    pageType: PageType.Home,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        minHeight: '150px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Banner, WidgetType.PromoCard],
    dataKey: 'ctaContent',
    dataContractType: DataContractType.PromoCardContent,
    order: 3,
    isUserDefined: false,
    tags: ['cta', 'promo'],
  },
  {
    id: 'home-footer',
    name: 'Footer',
    pageType: PageType.Home,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 4,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for PLP Page
  {
    id: 'plp-header',
    name: 'Header',
    pageType: PageType.PLP,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'filter-sidebar',
    name: 'Filter Sidebar',
    pageType: PageType.PLP,
    style: {
      minHeight: '500px',
      width: '20%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        width: '100%',
        minHeight: '200px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Filter],
    dataKey: 'filterContent',
    dataContractType: DataContractType.FilterContent,
    order: 1,
    isUserDefined: false,
    tags: ['sidebar', 'filters'],
  },
  {
    id: 'product-listing',
    name: 'Product Listing',
    pageType: PageType.PLP,
    style: {
      minHeight: '500px',
      width: '80%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
      gap: '16px',
      mobile: {
        width: '100%',
        gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
        gap: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.ProductGrid, WidgetType.Carousel],
    dataKey: 'productGridItems',
    dataContractType: DataContractType.ProductGridContent,
    order: 2,
    isUserDefined: false,
    tags: ['products'],
  },
  {
    id: 'plp-footer',
    name: 'Footer',
    pageType: PageType.PLP,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      }, tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 3,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for PDP Page
  {
    id: 'pdp-header',
    name: 'Header',
    pageType: PageType.PDP,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'product-image',
    name: 'Product Image',
    pageType: PageType.PDP,
    style: {
      minHeight: '400px',
      width: '50%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        width: '100%',
        minHeight: '300px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Banner],
    dataKey: 'productImageContent',
    dataContractType: DataContractType.BannerContent,
    order: 1,
    isUserDefined: false,
    tags: ['product', 'media'],
  },
  {
    id: 'product-details',
    name: 'Product Details',
    pageType: PageType.PDP,
    style: {
      minHeight: '400px',
      width: '50%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        width: '100%',
        minHeight: '300px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.AddToCart],
    dataKey: 'productDetailsContent',
    dataContractType: DataContractType.AddToCartContent,
    order: 2,
    isUserDefined: false,
    tags: ['product', 'details'],
  },
  {
    id: 'product-reviews',
    name: 'Product Reviews',
    pageType: PageType.PDP,
    style: {
      minHeight: '300px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        minHeight: '200px',
        padding: '8px',
      },
    },
    allowedWidgets: [WidgetType.Reviews],
    dataKey: 'reviewsContent',
    dataContractType: DataContractType.ReviewsContent,
    order: 3,
    isUserDefined: false,
    tags: ['product', 'reviews'],
  },
  {
    id: 'pdp-footer',
    name: 'Footer',
    pageType: PageType.PDP,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 4,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Search Page
  {
    id: 'search-header',
    name: 'Header',
    pageType: PageType.Search,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'search-bar',
    name: 'Search Bar',
    pageType: PageType.Search,
    style: {
      minHeight: '100px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        minHeight: '80px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.SearchBar],
    dataKey: 'searchBarContent',
    dataContractType: DataContractType.SearchBarContent,
    order: 1,
    isUserDefined: false,
    tags: ['search'],
  },
  {
    id: 'search-results',
    name: 'Search Results',
    pageType: PageType.Search,
    style: {
      minHeight: '500px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
      gap: '16px',
      mobile: {
        gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
        gap: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.ProductGrid, WidgetType.Carousel],
    dataKey: 'searchResultsContent',
    dataContractType: DataContractType.ProductGridContent,
    order: 2,
    isUserDefined: false,
    tags: ['search', 'products'],
  },
  {
    id: 'search-footer',
    name: 'Footer',
    pageType: PageType.Search,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 3,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Cart Page
  {
    id: 'cart-header',
    name: 'Header',
    pageType: PageType.Cart,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'cart-items',
    name: 'Cart Items',
    pageType: PageType.Cart,
    style: {
      minHeight: '400px',
      width: '70%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        width: '100%',
        minHeight: '300px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.ProductGrid],
    dataKey: 'cartItemsContent',
    dataContractType: DataContractType.ProductGridContent,
    order: 1,
    isUserDefined: false,
    tags: ['cart', 'products'],
  },
  {
    id: 'cart-summary',
    name: 'Cart Summary',
    pageType: PageType.Cart,
    style: {
      minHeight: '400px',
      width: '30%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        width: '100%',
        minHeight: '200px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.PromoCard],
    dataKey: 'cartSummaryContent',
    dataContractType: DataContractType.PromoCardContent,
    order: 2,
    isUserDefined: false,
    tags: ['cart', 'summary'],
  },
  {
    id: 'cart-footer',
    name: 'Footer',
    pageType: PageType.Cart,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 3,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Checkout Page
  {
    id: 'checkout-header',
    name: 'Header',
    pageType: PageType.Checkout,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'checkout-form',
    name: 'Checkout Form',
    pageType: PageType.Checkout,
    style: {
      minHeight: '500px',
      width: '60%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        width: '100%',
        minHeight: '400px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.PromoCard],
    dataKey: 'checkoutFormContent',
    dataContractType: DataContractType.PromoCardContent,
    order: 1,
    isUserDefined: false,
    tags: ['checkout', 'form'],
  },
  {
    id: 'checkout-summary',
    name: 'Checkout Summary',
    pageType: PageType.Checkout,
    style: {
      minHeight: '500px',
      width: '40%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        width: '100%',
        minHeight: '200px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.PromoCard],
    dataKey: 'checkoutSummaryContent',
    dataContractType: DataContractType.PromoCardContent,
    order: 2,
    isUserDefined: false,
    tags: ['checkout', 'summary'],
  },
  {
    id: 'checkout-footer',
    name: 'Footer',
    pageType: PageType.Checkout,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 3,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Blog Page
  {
    id: 'blog-header',
    name: 'Header',
    pageType: PageType.Blog,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'blog-posts',
    name: 'Blog Posts',
    pageType: PageType.Blog,
    style: {
      minHeight: '500px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
      gap: '16px',
      mobile: {
        gridTemplateColumns: '1fr',
        gap: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.BlogPost],
    dataKey: 'blogPostsContent',
    dataContractType: DataContractType.BlogPostContent,
    order: 1,
    isUserDefined: false,
    tags: ['blog', 'posts'],
  },
  {
    id: 'blog-footer',
    name: 'Footer',
    pageType: PageType.Blog,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 2,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Account Page
  {
    id: 'account-header',
    name: 'Header',
    pageType: PageType.Account,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'account-details',
    name: 'Account Details',
    pageType: PageType.Account,
    style: {
      minHeight: '400px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      mobile: {
        minHeight: '300px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.PromoCard],
    dataKey: 'accountDetailsContent',
    dataContractType: DataContractType.PromoCardContent,
    order: 1,
    isUserDefined: false,
    tags: ['account'],
  },
  {
    id: 'account-footer',
    name: 'Footer',
    pageType: PageType.Account,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 2,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Category Page
  {
    id: 'category-header',
    name: 'Header',
    pageType: PageType.Category,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'category-banner',
    name: 'Category Banner',
    pageType: PageType.Category,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        minHeight: '150px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Banner],
    dataKey: 'categoryBannerContent',
    dataContractType: DataContractType.BannerContent,
    order: 1,
    isUserDefined: false,
    tags: ['category', 'banner'],
  },
  {
    id: 'category-products',
    name: 'Category Products',
    pageType: PageType.Category,
    style: {
      minHeight: '500px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
      gap: '16px',
      mobile: {
        gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
        gap: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.ProductGrid, WidgetType.Carousel],
    dataKey: 'categoryProductsContent',
    dataContractType: DataContractType.ProductGridContent,
    order: 2,
    isUserDefined: false,
    tags: ['category', 'products'],
  },
  {
    id: 'category-footer',
    name: 'Footer',
    pageType: PageType.Category,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 3,
    isUserDefined: false,
    tags: ['footer'],
  },

  // Predefined Fragments for Promotions Page
  {
    id: 'promotions-header',
    name: 'Header',
    pageType: PageType.Promotions,
    style: {
      minHeight: '80px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '60px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Navigation],
    widget: WidgetType.Navigation,
    dataKey: 'navigationContent',
    dataContractType: DataContractType.NavigationContent,
    order: 0,
    isUserDefined: false,
    tags: ['header'],
  },
  {
    id: 'promotions-banner',
    name: 'Promotions Banner',
    pageType: PageType.Promotions,
    style: {
      minHeight: '300px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#E0E0E0',
      border: '1px solid #C0C0C0',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        minHeight: '200px',
        padding: '8px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Banner, WidgetType.Carousel],
    dataKey: 'promotionsBannerContent',
    dataContractType: DataContractType.BannerContent,
    order: 1,
    isUserDefined: false,
    tags: ['promo', 'banner'],
  },
  {
    id: 'promotions-grid',
    name: 'Promotions Grid',
    pageType: PageType.Promotions,
    style: {
      minHeight: '400px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#F5F5F5',
      border: '1px solid #C0C0C0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
      gap: '16px',
      mobile: {
        gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
        gap: '8px',
      },
    },
    allowedWidgets: [WidgetType.PromoCard],
    dataKey: 'promotionsGridContent',
    dataContractType: DataContractType.PromoCardContent,
    order: 2,
    isUserDefined: false,
    tags: ['promo', 'grid'],
  },
  {
    id: 'promotions-footer',
    name: 'Footer',
    pageType: PageType.Promotions,
    style: {
      minHeight: '200px',
      width: '100%',
      padding: '16px',
      backgroundColor: '#FFFFFF',
      border: '1px solid #C0C0C0',
      boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      mobile: {
        padding: '8px',
        minHeight: '150px',
      },
      tablet: {
        padding: '30px',
        minHeight: '120px',
      },
      desktop: {
        padding: '30px',
        minHeight: '120px',
      },
    },
    allowedWidgets: [WidgetType.Footer, WidgetType.SocialLinks],
    widget: WidgetType.Footer,
    dataKey: 'footerContent',
    dataContractType: DataContractType.FooterContent,
    order: 3,
    isUserDefined: false,
    tags: ['footer'],
  },
];

export default fragments;